### PR TITLE
Meal recipe api

### PR DESCRIPTION
**Pull request by uysalGokhan**
I added getmealrecipe functionality of api it gets random meal from https://www.themealdb.com/api.php and takes necessary datas from json format and make an HTTPRequest from this informations.
I also added 1 test for this functionality and test works fine currently. I benefit from some facts that are not going to change. If those facts change or a test throws an error, then it means there is something wrong.

### CODE REVIEW

**Comment by uysalGokhan** [comment]
I added getmealrecipebyname functionality of api it gets random meal from www.themealdb.com/api/json/v1/1/search.php?s="meal_Name" and takes necessary datas from json format and make an HTTPRequest from this informations.
I also added 2 test for this functionality and tests are works fine currently. I benefit from some facts that are not going to change. If those facts change or a test throws an error, then it means there is something wrong.

**Comment by faruknane** [comment]
I think the functionality "get random meal recipe" is well implemented! However, for "get meal recipe by name" it could be in a better form that is more parsable. Overall, it is a decent implementation.

**Comment by cwtaras** [comment]
If you can review the code, and think it is okay, we can merge it to the master

**Comment by faruknane** [comment]
I quickly reviewed the code. I think the functionality "get random meal recipe" is well implemented! However, for "get meal recipe by name" it could be in a better form that is more parsable. Overall, it is a decent implementation.

**Comment by mssentop** [comment]
I also reviewed the code and there does not seem to be any problem after our joint examination on discord. It is convenient for merging now.

**Pull request merged**
