### PR TITLE
event model creation to use weather-api  

### PR DESCRIPTION
**Pull request by mmuhammetcavus**
I added event model and event-creation html file. Please review them and let me know if there is anything wrong.

### CODE REVIEW

**Comment by uysalGokhan** [comment]
I think in the urls.py path variable should not be empty for weather-api url path

**Comment by faruknane** [comment]
Adding events into the database is a good idea! Also in your API implementation, you check whether the 3rd API response is ok to detect if there is an error. You are handling that case. That's a nice and clean code. Great job!

**Comment by cwtaras** [comment]
We can merge it after @mmuhammetcavus makes the necessary changes.

**Comment by mmuhammetcavus** [comment]
You guys are right.  I overlooked those things. I am gonna fix those problems right away. Thanks

**Comment by mmuhammetcavus** [comment]
I will clsoe this pull request now and after I fixed my code, I will send another pull request.

**Pull request closed without merging**
